### ISSUE TITLE
Bugs: Calculation of total_fee and expired_date

### ISSUE THREAD

**Issue by LYZhelloworld** [zhuhank/wechat-payment-for-woocommerce#1]
class-wc-wechatpay.php (357):
`$totalFee = round($totalFee * $this->exchange_rate, 2);`
`$totalFee = round($totalFee * $this->exchange_rate);`

class-wc-wechatpay.php (364):
`- $expiredTime = $startTime + 600;`
`+ $expiredTime = $date->add(new DateInterval('PT6M'))->format('YmdHis');`

**Comment by sajjad606** [comment]
hi, if you are in iran you can pay any forign payments via our web site.
سایت EPAY 724 | خدمات ارزی بین الملل (https://bit.ly/3uieWwW) (سایت EPAY 724 | خدمات ارزی بین الملل (https://bit.ly/3rW9MEG))
online payments for application fees, buying gift cards, international exams fees are easier than ever ….
